export const COMPANY = {
  nomCommercial: "MGP ELEC",
  formeJuridique: "Entrepreneur individuel",
  dirigeant: "Gaïus Perrier",
  siren: "929986180",
  adresse: "314 Chemin Jeanson, RDM Les Bas",
  codePostal: "97440",
  ville: "Saint-André",
  departement: "La Réunion (974)",
  telephone: "06 92 38 30 69",
  telephoneHref: "tel:+262692383069",
  email: "contact@mgpelec.re",
  site: "www.mgpelec.re",
  siteHref: "https://www.mgpelec.re",
  hebergeur: {
    nom: "OVH SAS",
    adresse: "2 rue Kellermann, 59100 Roubaix, France",
    site: "www.ovhcloud.com",
  },
  hebergementApplicatif: {
    nom: "Vercel Inc.",
    adresse: "440 N Barranca Ave #4133, Covina, CA 91723, États-Unis",
    site: "vercel.com",
  },
  assurance: {
    compagnie: "AXERIA IARD",
    courtier: "APRIL",
    contrat: "26056748729",
    garanties: ["Responsabilité civile professionnelle", "Responsabilité civile décennale"],
    validiteDebut: "01/06/2026",
    validiteFin: "31/12/2026",
    activitesAssurees: [
      "Électricité",
      "Télécommunication",
      "Alarmes intrusion",
      "Alarmes incendie",
    ],
  },
  slogan: "Que le courant passe",
} as const;
